//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public Report()
        {
            this.EmployeeReports = new HashSet<EmployeeReport>();
        }
    
        public int ReportId { get; set; }
        public DateTime TimeOfReport { get; set; }
    
        public virtual ICollection<EmployeeReport> EmployeeReports { get; set; }
    }
}